import React, { useState, useEffect } from 'react';
import { api } from '../../lib/api';
import { Question, DiagnosticSession, DiagnosticResult } from '../../types';
import Button from '../ui/Button';
import Card from '../ui/Card';
import StatusMessage from '../ui/StatusMessage';
import LoadingState from '../ui/LoadingState';
import { HelpCircle, Sparkles, CheckCircle2, AlertCircle, ArrowUpRight } from 'lucide-react';

interface UnderstandingCheckProps {
  topicId: string;
  topicTitle: string;
  onWeaknessDetected?: () => void;
  onSuccessCheck?: () => void;
}

export default function UnderstandingCheck({
  topicId,
  topicTitle,
  onWeaknessDetected,
  onSuccessCheck
}: UnderstandingCheckProps) {
  const [session, setSession] = useState<DiagnosticSession | null>(null);
  const [question, setQuestion] = useState<Question | null>(null);
  const [studentAnswer, setStudentAnswer] = useState('');
  
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const [result, setResult] = useState<DiagnosticResult | null>(null);

  // Reset states on topic change
  useEffect(() => {
    setSession(null);
    setQuestion(null);
    setStudentAnswer('');
    setResult(null);
    setError(null);
  }, [topicId]);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    setStudentAnswer('');
    try {
      // 1. Generate check session
      const sess: DiagnosticSession = await api.generateUnderstandingCheck(topicId);
      setSession(sess);

      // 2. Fetch the question details
      const questions: Question[] = await api.getSessionQuestions(sess.id);
      if (questions && questions.length > 0) {
        setQuestion(questions[0]);
      } else {
        throw new Error('No assessment questions generated by Learniverse AI engine.');
      }
    } catch (err: any) {
      setError(err.message || 'Failed to generate understanding booster question.');
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!studentAnswer.trim() || !session || !question) return;

    setSubmitting(true);
    setError(null);
    try {
      const payload = {
        answers: [
          {
            question_id: question.id,
            student_answer: studentAnswer
          }
        ]
      };
      // Submit choices
      await api.submitSessionAnswers(session.id, payload);

      // Get scoring & checkmarks outcome
      const res: DiagnosticResult = await api.getSessionResult(session.id);
      setResult(res);

      if (res.percentage < 70) {
        if (onWeaknessDetected) onWeaknessDetected();
      } else {
        if (onSuccessCheck) onSuccessCheck();
      }
    } catch (err: any) {
      setError(err.message || 'Could not submit assessment response.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Card className="border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/50 p-5 md:p-6 rounded-2xl relative space-y-4">
      {/* Block Header */}
      <div className="flex justify-between items-start border-b border-slate-100 dark:border-slate-800 pb-3">
        <div className="space-y-1">
          <div className="text-[9px] font-black tracking-[0.2em] text-blue-600 dark:text-blue-400 uppercase">
            Diagostic Probe
          </div>
          <h4 className="text-sm font-black text-slate-800 dark:text-white heading-font">
            QUICK UNDERSTANDING CHECK
          </h4>
        </div>
        {!session && (
          <Button size="sm" variant="secondary" onClick={handleGenerate} isLoading={loading}>
            <Sparkles className="h-3 w-3 mr-1" /> Boost Diagnostics
          </Button>
        )}
      </div>

      {loading && <LoadingState message="Generating custom short-answer booster..." />}

      {error && (
        <StatusMessage type="error" message={error} onRetry={handleGenerate} />
      )}

      {/* active check screen */}
      {session && question && !result && (
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800">
            <span className="text-[10px] uppercase font-bold text-slate-400 dark:text-slate-500 block mb-1">Question</span>
            <p className="text-sm font-semibold text-slate-800 dark:text-slate-100 leading-relaxed">
              {question.question_text}
            </p>
          </div>

          <div className="space-y-2">
            <label className="text-[10px] uppercase font-bold text-slate-400 dark:text-slate-500 mb-1 block">Your Explanation</label>
            <textarea
              value={studentAnswer}
              onChange={(e) => setStudentAnswer(e.target.value)}
              placeholder="State your answer based on physical chemistry, physics, or biology standards..."
              className="w-full min-h-[90px] p-3 text-sm rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 placeholder:text-slate-400 dark:placeholder:text-slate-600 outline-hidden focus:border-blue-500/60 focus:ring-4 focus:ring-blue-500/5 dark:focus:ring-blue-400/5"
              required
            />
          </div>

          <div className="flex justify-between items-center gap-4">
            <Button size="sm" variant="ghost" onClick={() => { setSession(null); setQuestion(null); }} disabled={submitting}>
              Reset
            </Button>
            <Button size="sm" type="submit" isLoading={submitting} disabled={!studentAnswer.trim()}>
              Submit Explanation
            </Button>
          </div>
        </form>
      )}

      {/* Result review display panel */}
      {result && (
        <div className="space-y-4 pt-2">
          {/* outcome widget badge */}
          <div className={`p-4 rounded-xl border flex items-center gap-3.5 ${
            result.percentage >= 70 
              ? 'bg-emerald-50 dark:bg-emerald-950/20 border-emerald-200 dark:border-emerald-900/30 text-emerald-800 dark:text-emerald-400'
              : 'bg-amber-50 dark:bg-amber-950/20 border-amber-200 dark:border-amber-900/30 text-amber-800 dark:text-amber-400'
          }`}>
            {result.percentage >= 70 ? (
              <CheckCircle2 className="h-6 w-6 shrink-0 text-emerald-500" />
            ) : (
              <AlertCircle className="h-6 w-6 shrink-0 text-amber-500" />
            )}
            <div className="space-y-0.5">
              <div className="text-xs uppercase font-bold tracking-wider">
                {result.outcome || 'Assessment Result'}
              </div>
              <p className="text-sm">
                Score: <strong className="font-extrabold">{result.score}/{result.max_score}</strong> ({result.percentage}%)
              </p>
            </div>
          </div>

          {/* detail reviews */}
          {result.details && result.details.map((det, idx) => (
            <div key={idx} className="space-y-3 p-4 rounded-xl border border-slate-150 dark:border-slate-800">
              <div>
                <span className="text-[9px] uppercase font-bold text-slate-400 dark:text-slate-500 block">Question</span>
                <p className="text-xs font-bold text-slate-800 dark:text-slate-100">{det.question_text}</p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs border-t border-b border-slate-100 dark:border-slate-800/60 py-2">
                <div>
                  <span className="text-[#94A3B8] font-bold block mb-0.5">Your Response:</span>
                  <p className="italic text-slate-700 dark:text-slate-300">{det.student_answer || '(Empty)'}</p>
                </div>
                <div>
                  <span className="text-emerald-500 font-bold block mb-0.5">Approved Sample solution:</span>
                  <p className="text-emerald-605 dark:text-emerald-400/90 leading-relaxed font-semibold">{det.correct_answer}</p>
                </div>
              </div>
              <div className="space-y-1">
                <span className="text-[9px] uppercase font-bold text-blue-500 dark:text-indigo-400 block">AI Evaluation Feedback</span>
                <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">{det.feedback}</p>
                {det.explanation && (
                  <p className="text-xs text-slate-400 dark:text-slate-500 mt-1 leading-normal italic">
                    <strong>Note:</strong> {det.explanation}
                  </p>
                )}
              </div>
            </div>
          ))}

          {/* remedial call to action */}
          {result.percentage < 70 ? (
            <div className="bg-amber-500/5 dark:bg-amber-400/5 p-4 rounded-xl border border-amber-500/10 dark:border-amber-400/10 flex flex-col md:flex-row justify-between items-center gap-3">
              <div className="space-y-1">
                <span className="text-xs font-extrabold text-amber-700 dark:text-amber-400 uppercase tracking-wider block">Weakness Detected</span>
                <p className="text-xs text-slate-600 dark:text-slate-450">
                  Your response indicates gaps in current standard knowledge. Let's practice with the complete Diagnostic Quiz to locate specific components.
                </p>
              </div>
              <Button size="sm" variant="primary" onClick={onWeaknessDetected} className="bg-amber-500 dark:bg-amber-500 hover:bg-amber-600 dark:text-slate-950">
                Trigger Full Quiz <ArrowUpRight className="h-3 ml-1" />
              </Button>
            </div>
          ) : (
            <div className="text-center p-3">
              <p className="text-xs text-slate-500 dark:text-slate-450 pb-2">Excellent performance! Click below to probe again or try another chapter check.</p>
              <Button size="sm" variant="secondary" onClick={handleGenerate}>
                Check Another Question
              </Button>
            </div>
          )}
        </div>
      )}
    </Card>
  );
}
